import nock from "nock";

nock("https://fake-api.play.postgrest.local:443", {
  encodedQueryParams: true,
})
  .post("/posts", [
    { title: "foo", slug: "foo-bar", content: "bar", categoryId: 2 },
    { title: "foo-2", slug: "foo-bar-2", content: "bar-2", categoryId: 1 },
  ])
  .query({
    columns: "%22title%22%2C%22slug%22%2C%22content%22%2C%22categoryId%22",
    select: "%2A",
  })
  .reply(
    201,
    [
      {
        id: 12895,
        title: "foo",
        slug: "foo-bar",
        createdAt: "2024-04-25T09:00:47.766685+00:00",
        content: "bar",
        categoryId: 2,
        images: null,
      },
      {
        id: 12896,
        title: "foo-2",
        slug: "foo-bar-2",
        createdAt: "2024-04-25T09:00:47.766685+00:00",
        content: "bar-2",
        categoryId: 1,
        images: null,
      },
    ],
    [
      "Date",
      "Thu, 25 Apr 2024 09:00:47 GMT",
      "Content-Type",
      "application/json; charset=utf-8",
      "Transfer-Encoding",
      "chunked",
      "Connection",
      "close",
      "Content-Range",
      "*/*",
      "CF-Ray",
      "879d250dca78778e-IST",
      "CF-Cache-Status",
      "DYNAMIC",
      "Access-Control-Allow-Origin",
      "*",
      "Strict-Transport-Security",
      "max-age=15552000; includeSubDomains",
      "Via",
      "kong/2.8.1",
      "content-profile",
      "public",
      "sb-gateway-version",
      "1",
      "x-kong-proxy-latency",
      "0",
      "x-kong-upstream-latency",
      "5",
      "Vary",
      "Accept-Encoding",
      "Server",
      "cloudflare",
      "alt-svc",
      'h3=":443"; ma=86400',
    ],
  );

nock("https://fake-api.play.postgrest.local:443", {
  encodedQueryParams: true,
})
  .post("/posts", [
    { title: "foo", slug: "foo-bar", content: "bar", categoryId: 2 },
    { title: "foo-2", slug: "foo-bar-2", content: "bar-2", categoryId: 1 },
  ])
  .query({
    columns: "%22title%22%2C%22slug%22%2C%22content%22%2C%22categoryId%22",
    select: "%2A",
  })
  .reply(
    201,
    [
      {
        id: 12897,
        title: "foo",
        slug: "foo-bar",
        createdAt: "2024-04-25T09:00:48.264931+00:00",
        content: "bar",
        categoryId: 2,
        images: null,
      },
      {
        id: 12898,
        title: "foo-2",
        slug: "foo-bar-2",
        createdAt: "2024-04-25T09:00:48.264931+00:00",
        content: "bar-2",
        categoryId: 1,
        images: null,
      },
    ],
    [
      "Date",
      "Thu, 25 Apr 2024 09:00:48 GMT",
      "Content-Type",
      "application/json; charset=utf-8",
      "Transfer-Encoding",
      "chunked",
      "Connection",
      "close",
      "Content-Range",
      "*/*",
      "CF-Ray",
      "879d25103a3b693e-IST",
      "CF-Cache-Status",
      "DYNAMIC",
      "Access-Control-Allow-Origin",
      "*",
      "Strict-Transport-Security",
      "max-age=15552000; includeSubDomains",
      "Via",
      "kong/2.8.1",
      "content-profile",
      "public",
      "sb-gateway-version",
      "1",
      "x-kong-proxy-latency",
      "2",
      "x-kong-upstream-latency",
      "4",
      "Vary",
      "Accept-Encoding",
      "Server",
      "cloudflare",
      "alt-svc",
      'h3=":443"; ma=86400',
    ],
  );

nock("https://fake-api.play.postgrest.local:443", {
  encodedQueryParams: true,
})
  .post("/posts", [])
  .query({ select: "%2A" })
  .reply(
    406,
    {
      code: "PGRST106",
      details: null,
      hint: null,
      message: "The schema must be one of the following: public, storage",
    },
    [
      "Date",
      "Thu, 25 Apr 2024 09:00:48 GMT",
      "Content-Type",
      "application/json; charset=utf-8",
      "Transfer-Encoding",
      "chunked",
      "Connection",
      "close",
      "CF-Ray",
      "879d25125ed67240-IST",
      "CF-Cache-Status",
      "DYNAMIC",
      "Access-Control-Allow-Origin",
      "*",
      "Strict-Transport-Security",
      "max-age=15552000; includeSubDomains",
      "Via",
      "kong/2.8.1",
      "sb-gateway-version",
      "1",
      "x-kong-proxy-latency",
      "0",
      "x-kong-upstream-latency",
      "1",
      "Vary",
      "Accept-Encoding",
      "Server",
      "cloudflare",
      "alt-svc",
      'h3=":443"; ma=86400',
    ],
  );
